ALTER TABLE employee_records
  ADD COLUMN phone VARCHAR(32) NULL AFTER email,
  ADD COLUMN birthDate DATE NULL AFTER phone,
  ADD COLUMN cpf VARCHAR(32) NULL AFTER birthDate,
  ADD COLUMN rg VARCHAR(32) NULL AFTER cpf,
  ADD COLUMN zipCode VARCHAR(16) NULL AFTER rg,
  ADD COLUMN address VARCHAR(255) NULL AFTER zipCode,
  ADD COLUMN addressNumber VARCHAR(32) NULL AFTER address,
  ADD COLUMN addressComplement VARCHAR(160) NULL AFTER addressNumber,
  ADD COLUMN neighborhood VARCHAR(160) NULL AFTER addressComplement,
  ADD COLUMN city VARCHAR(160) NULL AFTER neighborhood,
  ADD COLUMN state VARCHAR(2) NULL AFTER city,
  ADD COLUMN professionalLicenseType VARCHAR(32) NULL AFTER department,
  ADD COLUMN professionalLicenseNumber VARCHAR(80) NULL AFTER professionalLicenseType,
  ADD COLUMN professionalLicenseState VARCHAR(2) NULL AFTER professionalLicenseNumber,
  ADD COLUMN digitalCertificateStatus ENUM('not_registered','registered','expired','revoked') NOT NULL DEFAULT 'not_registered' AFTER internalNotes,
  ADD COLUMN digitalCertificateType VARCHAR(80) NULL AFTER digitalCertificateStatus,
  ADD COLUMN digitalCertificateSubject VARCHAR(255) NULL AFTER digitalCertificateType,
  ADD COLUMN digitalCertificateIssuer VARCHAR(255) NULL AFTER digitalCertificateSubject,
  ADD COLUMN digitalCertificateSerial VARCHAR(160) NULL AFTER digitalCertificateIssuer,
  ADD COLUMN digitalCertificateValidUntil DATE NULL AFTER digitalCertificateSerial,
  ADD COLUMN digitalCertificateFingerprint VARCHAR(128) NULL AFTER digitalCertificateValidUntil,
  ADD COLUMN digitalCertificateNotes TEXT NULL AFTER digitalCertificateFingerprint,
  ADD COLUMN digitalCertificateUpdatedAt DATETIME NULL AFTER digitalCertificateNotes,
  ADD COLUMN digitalCertificateUpdatedByUserId INT NULL AFTER digitalCertificateUpdatedAt;
