CREATE TABLE IF NOT EXISTS whatsapp_message_logs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  provider VARCHAR(64) NOT NULL DEFAULT 'meta_cloud_api',
  direction ENUM('outbound','inbound','status') NOT NULL,
  purpose VARCHAR(96) NULL,
  patientId INT NULL,
  appointmentId INT NULL,
  documentType VARCHAR(64) NULL,
  documentId INT NULL,
  phone VARCHAR(32) NULL,
  messageType VARCHAR(32) NULL,
  templateName VARCHAR(128) NULL,
  content TEXT NULL,
  providerMessageId VARCHAR(255) NULL,
  status VARCHAR(64) NOT NULL DEFAULT 'pending',
  rawPayload JSON NULL,
  errorMessage TEXT NULL,
  createdBy INT NULL,
  createdAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updatedAt TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_whatsapp_message_provider_id (providerMessageId),
  KEY idx_whatsapp_message_patient (patientId),
  KEY idx_whatsapp_message_appointment (appointmentId),
  KEY idx_whatsapp_message_phone (phone),
  KEY idx_whatsapp_message_created (createdAt)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
