import "dotenv/config";
import { runLegacyAnamneseBackfill } from "../server/lib/legacy-anamnese-backfill.ts";

const LEGACY_QUESTION_TEXT: Record<string, string> = {
  "73693": "Tem alergia a algum medicamento, alimento ou substância?",
  "73694": "Faz uso de algum medicamento contínuo?",
  "79783": "Selecione os problemas de saúde que tem atualmente",
  "79784": "Teve gestações? Se sim, quando foi o último parto?",
  "80248": "Profissão",
  "80249": "Estado civil",
  "80250": "Cidade e estado em que mora",
  "80251": "Consome bebida alcoólica?",
  "80252": "Usa método anticoncepcional? Qual?",
  "80253": "Toma vitamina D? Qual a dose e em que frequência?",
  "80254": "Está gestante ou lactante?",
  "80255": "Já teve problemas de cicatrização, como queloides?",
  "80256": "Já teve alguma reação ruim com anestesia?",
  "80257": "Já teve trombose, embolia ou AVC?",
  "80258": "Já teve alguma hemorragia? (como evacuar ou vomitar sangue?)",
  "80259": "Realiza atividade física regular?",
  "80260": "Você é muito sensível à dor?",
  "80261": "Já realizou alguma cirurgia?",
  "80262": "Usa alguma droga ilícita?",
  "80263": "Usa algum tipo de hormônio?",
  "80264": "Faz uso de medicamentos regularmente?",
  "81028": "Há algo que gostaria de informar ao médico?",
  "82417": "Tem alergia a algum medicamento, alimento ou substância?",
  "82868": "Peso atual aproximado em kg",
  "82869": "Sua estatura aproximada (em metros)",
  "82871": "Tem alergia a algum medicamento, alimento ou substância?",
  "82872": "Faz uso de anticoagulante? (ou AAS?)",
  "82873": "Selecione os problemas de saúde que tem atualmente",
  "82875": "Profissão",
  "82876": "Estado civil",
  "82877": "Cidade e estado em que mora",
  "82878": "Consome bebida alcoólica?",
  "82880": "Toma vitamina D? Qual a dose e em que frequência?",
  "82882": "Já teve problemas de cicatrização, como queloides?",
  "82883": "Já teve alguma reação ruim com anestesia?",
  "82884": "Já teve alguma hemorragia? (como evacuar ou vomitar sangue?)",
  "82885": "Já teve trombose, embolia ou AVC?",
  "82886": "Realiza atividade física regular?",
  "82887": "Você é muito sensível à dor?",
  "82888": "Já realizou alguma cirurgia?",
  "82889": "Usa alguma droga ilícita?",
  "82890": "Usa algum tipo de hormônio?",
  "82891": "Faz uso de medicamentos regularmente?",
  "82892": "Tem ou já teve pedras nos rins?",
  "82893": "Peso atual aproximado em kg",
  "82894": "Sua estatura aproximada (em metros)",
  "90360": "É fumante?",
  "90361": "Faz uso de anticoagulante? (ou AAS?)",
  "91018": "Tem ou já teve pedras nos rins?",
  "92953": "Há algo que gostaria de informar ao médico?",
};

const dryRun = process.env.DRY_RUN === "1" || process.argv.includes("--dry-run");

const summary = await runLegacyAnamneseBackfill(LEGACY_QUESTION_TEXT, { dryRun });
console.log(JSON.stringify(summary, null, 2));
